/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateCashRouteImport } from './routes/private-cash'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TokensTokenIdRouteImport } from './routes/tokens.$tokenId'
import { Route as ApiMeRouteImport } from './routes/api.me'
import { Route as ApiAssetsRouteImport } from './routes/api.assets'
import { Route as ApiTokenTokenIdRouteImport } from './routes/api.token.$tokenId'
import { Route as ApiWalletsWalletIdTransactionsRouteImport } from './routes/api.wallets.$walletId.transactions'
import { Route as ApiTokenTokenIdAssetRouteImport } from './routes/api.token.$tokenId.asset'
import { Route as ApiAssetsAssetIdTransactionsRouteImport } from './routes/api.assets.$assetId.transactions'

const PrivateCashRoute = PrivateCashRouteImport.update({
  id: '/private-cash',
  path: '/private-cash',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensTokenIdRoute = TokensTokenIdRouteImport.update({
  id: '/tokens/$tokenId',
  path: '/tokens/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsRoute = ApiAssetsRouteImport.update({
  id: '/api/assets',
  path: '/api/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokenTokenIdRoute = ApiTokenTokenIdRouteImport.update({
  id: '/api/token/$tokenId',
  path: '/api/token/$tokenId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWalletsWalletIdTransactionsRoute =
  ApiWalletsWalletIdTransactionsRouteImport.update({
    id: '/api/wallets/$walletId/transactions',
    path: '/api/wallets/$walletId/transactions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTokenTokenIdAssetRoute = ApiTokenTokenIdAssetRouteImport.update({
  id: '/asset',
  path: '/asset',
  getParentRoute: () => ApiTokenTokenIdRoute,
} as any)
const ApiAssetsAssetIdTransactionsRoute =
  ApiAssetsAssetIdTransactionsRouteImport.update({
    id: '/$assetId/transactions',
    path: '/$assetId/transactions',
    getParentRoute: () => ApiAssetsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/login': typeof LoginRoute
  '/private-cash': typeof PrivateCashRoute
  '/api/assets': typeof ApiAssetsRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/tokens/$tokenId': typeof TokensTokenIdRoute
  '/api/token/$tokenId': typeof ApiTokenTokenIdRouteWithChildren
  '/api/assets/$assetId/transactions': typeof ApiAssetsAssetIdTransactionsRoute
  '/api/token/$tokenId/asset': typeof ApiTokenTokenIdAssetRoute
  '/api/wallets/$walletId/transactions': typeof ApiWalletsWalletIdTransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/login': typeof LoginRoute
  '/private-cash': typeof PrivateCashRoute
  '/api/assets': typeof ApiAssetsRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/tokens/$tokenId': typeof TokensTokenIdRoute
  '/api/token/$tokenId': typeof ApiTokenTokenIdRouteWithChildren
  '/api/assets/$assetId/transactions': typeof ApiAssetsAssetIdTransactionsRoute
  '/api/token/$tokenId/asset': typeof ApiTokenTokenIdAssetRoute
  '/api/wallets/$walletId/transactions': typeof ApiWalletsWalletIdTransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/login': typeof LoginRoute
  '/private-cash': typeof PrivateCashRoute
  '/api/assets': typeof ApiAssetsRouteWithChildren
  '/api/me': typeof ApiMeRoute
  '/tokens/$tokenId': typeof TokensTokenIdRoute
  '/api/token/$tokenId': typeof ApiTokenTokenIdRouteWithChildren
  '/api/assets/$assetId/transactions': typeof ApiAssetsAssetIdTransactionsRoute
  '/api/token/$tokenId/asset': typeof ApiTokenTokenIdAssetRoute
  '/api/wallets/$walletId/transactions': typeof ApiWalletsWalletIdTransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/login'
    | '/private-cash'
    | '/api/assets'
    | '/api/me'
    | '/tokens/$tokenId'
    | '/api/token/$tokenId'
    | '/api/assets/$assetId/transactions'
    | '/api/token/$tokenId/asset'
    | '/api/wallets/$walletId/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/login'
    | '/private-cash'
    | '/api/assets'
    | '/api/me'
    | '/tokens/$tokenId'
    | '/api/token/$tokenId'
    | '/api/assets/$assetId/transactions'
    | '/api/token/$tokenId/asset'
    | '/api/wallets/$walletId/transactions'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/login'
    | '/private-cash'
    | '/api/assets'
    | '/api/me'
    | '/tokens/$tokenId'
    | '/api/token/$tokenId'
    | '/api/assets/$assetId/transactions'
    | '/api/token/$tokenId/asset'
    | '/api/wallets/$walletId/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  LoginRoute: typeof LoginRoute
  PrivateCashRoute: typeof PrivateCashRoute
  ApiAssetsRoute: typeof ApiAssetsRouteWithChildren
  ApiMeRoute: typeof ApiMeRoute
  TokensTokenIdRoute: typeof TokensTokenIdRoute
  ApiTokenTokenIdRoute: typeof ApiTokenTokenIdRouteWithChildren
  ApiWalletsWalletIdTransactionsRoute: typeof ApiWalletsWalletIdTransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/private-cash': {
      id: '/private-cash'
      path: '/private-cash'
      fullPath: '/private-cash'
      preLoaderRoute: typeof PrivateCashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens/$tokenId': {
      id: '/tokens/$tokenId'
      path: '/tokens/$tokenId'
      fullPath: '/tokens/$tokenId'
      preLoaderRoute: typeof TokensTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets': {
      id: '/api/assets'
      path: '/api/assets'
      fullPath: '/api/assets'
      preLoaderRoute: typeof ApiAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/token/$tokenId': {
      id: '/api/token/$tokenId'
      path: '/api/token/$tokenId'
      fullPath: '/api/token/$tokenId'
      preLoaderRoute: typeof ApiTokenTokenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wallets/$walletId/transactions': {
      id: '/api/wallets/$walletId/transactions'
      path: '/api/wallets/$walletId/transactions'
      fullPath: '/api/wallets/$walletId/transactions'
      preLoaderRoute: typeof ApiWalletsWalletIdTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/token/$tokenId/asset': {
      id: '/api/token/$tokenId/asset'
      path: '/asset'
      fullPath: '/api/token/$tokenId/asset'
      preLoaderRoute: typeof ApiTokenTokenIdAssetRouteImport
      parentRoute: typeof ApiTokenTokenIdRoute
    }
    '/api/assets/$assetId/transactions': {
      id: '/api/assets/$assetId/transactions'
      path: '/$assetId/transactions'
      fullPath: '/api/assets/$assetId/transactions'
      preLoaderRoute: typeof ApiAssetsAssetIdTransactionsRouteImport
      parentRoute: typeof ApiAssetsRoute
    }
  }
}

interface ApiAssetsRouteChildren {
  ApiAssetsAssetIdTransactionsRoute: typeof ApiAssetsAssetIdTransactionsRoute
}

const ApiAssetsRouteChildren: ApiAssetsRouteChildren = {
  ApiAssetsAssetIdTransactionsRoute: ApiAssetsAssetIdTransactionsRoute,
}

const ApiAssetsRouteWithChildren = ApiAssetsRoute._addFileChildren(
  ApiAssetsRouteChildren,
)

interface ApiTokenTokenIdRouteChildren {
  ApiTokenTokenIdAssetRoute: typeof ApiTokenTokenIdAssetRoute
}

const ApiTokenTokenIdRouteChildren: ApiTokenTokenIdRouteChildren = {
  ApiTokenTokenIdAssetRoute: ApiTokenTokenIdAssetRoute,
}

const ApiTokenTokenIdRouteWithChildren = ApiTokenTokenIdRoute._addFileChildren(
  ApiTokenTokenIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  LoginRoute: LoginRoute,
  PrivateCashRoute: PrivateCashRoute,
  ApiAssetsRoute: ApiAssetsRouteWithChildren,
  ApiMeRoute: ApiMeRoute,
  TokensTokenIdRoute: TokensTokenIdRoute,
  ApiTokenTokenIdRoute: ApiTokenTokenIdRouteWithChildren,
  ApiWalletsWalletIdTransactionsRoute: ApiWalletsWalletIdTransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
